### ISSUE TITLE
No Output At All

### ISSUE THREAD

**Issue by bensooter** [hirokidaichi/goviz#12]
Running goviz generates no output at all, I don't even get the help message with -h.  No commands provide any output at all.  It was installed with `go get github.com/hirokidaichi/goviz`.  Using go version 1.6.3 on Ubuntu 16.04.1.

**Comment by gosharplite** [comment]
Same with go1.7

**Comment by jurij** [comment]
had the same problem. it has nothing todo with the go version. see pull request https://github.com/hirokidaichi/goviz/pull/8/commits/63190e5ad68ceb6cc1fbc8faf64ec59b40534fcb

**Comment by bensooter** [comment]
Thanks @juRiii that fixed it for me.

**Comment by yanpozka** [comment]
I'm still not seeing any output at all, nothing nor with -h nor -m nor -l nothing. Is anyone having the same issue ?
I'm running Ubuntu 16.04, **uname** output:
```
Linux nonoy 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Go version:
```
go version go1.8.3 linux/amd64
```

**Comment by tbtommyb** [comment]
I am also seeing no output at all on Go 1.8.3 on Ubuntu 16.04.03.

**Comment by chanyoung** [comment]
Same problem on Go 1.8.3 on Ubuntu 16.04.1.
