### ISSUE TITLE
Unable to handle GOPATH with multiple paths.

### ISSUE THREAD

**Issue by mewmew** [hirokidaichi/goviz#4]
```
export GOPATH=/tmp/go_a:/tmp/go_b
go get github.com/hirokidaichi/goviz
goviz -i github.com/hirokidaichi/goviz
// Output:
// inputdir does not exist.
// go get github.com/hirokidaichi/goviz
```

**Comment by xtaci** [comment]
please merge, same problem encountered!

**Comment by mewmew** [comment]
As this issue was reported over 1 year ago, and the pull request received no response, it does not seem likely that it will be solved for quite some time. Closing this issue for now, it can easily be re-opened if the situation changes.

Still, thanks for a lovely project! Cheers /u
